# -*- coding: utf-8 -*-

SendBillSync = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillSync', 
   'body': '\n            <wcf:SendBillSync>\n                <!--Optional:-->\n                <wcf:fileName>%(zip_fileName)s</wcf:fileName>\n                <!--Optional:-->\n                <wcf:contentFile>%(zip_data)s</wcf:contentFile>\n            </wcf:SendBillSync>\n        ', 
   'DianResponse': '{http://schemas.datacontract.org/2004/07/DianResponse}DianResponse', 
   'ErrorMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}ErrorMessage', 
   'string': '{http://schemas.microsoft.com/2003/10/Serialization/Arrays}string', 
   'IsValid': '{http://schemas.datacontract.org/2004/07/DianResponse}IsValid', 
   'StatusCode': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusCode', 
   'StatusDescription': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusDescription', 
   'StatusMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusMessage', 
   'XmlDocumentKey': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlDocumentKey', 
   'XmlBase64Bytes': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlBase64Bytes', 
   'IssueTime': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueTime', 
   'IssueDate': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueDate', 
   'LineResponse': '{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LineResponse'}
SendBillAsync = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAsync', 
   'body': '\n            <wcf:SendBillAsync>\n                <!--Optional:-->\n                <wcf:fileName>%(zip_fileName)s</wcf:fileName>\n                <!--Optional:-->\n                <wcf:contentFile>%(zip_data)s</wcf:contentFile>\n            </wcf:SendBillAsync>\n        ', 
   'ZipKey': '{http://schemas.datacontract.org/2004/07/UploadDocumentResponse}ZipKey', 
   'ErrorMessageList': '{http://schemas.datacontract.org/2004/07/UploadDocumentResponse}ErrorMessageList'}
SendTestSetAsync = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/SendTestSetAsync', 
   'body': '\n            <wcf:SendTestSetAsync>\n                <!--Optional:-->\n                <wcf:fileName>%(zip_fileName)s</wcf:fileName>\n                <!--Optional:-->\n                <wcf:contentFile>%(zip_data)s</wcf:contentFile>\n                <!--Optional:-->\n                <wcf:testSetId>%(TestSetId)s</wcf:testSetId>\n            </wcf:SendTestSetAsync>\n        ', 
   'ZipKey': '{http://schemas.datacontract.org/2004/07/UploadDocumentResponse}ZipKey', 
   'ErrorMessageList': '{http://schemas.datacontract.org/2004/07/UploadDocumentResponse}ErrorMessageList'}
GetStatusZip = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusZip', 
   'body': '\n            <wcf:GetStatusZip>\n                <!--Optional:-->\n                <wcf:trackId>%(trackId)s</wcf:trackId>\n            </wcf:GetStatusZip>\n        ', 
   'DianResponse': '{http://schemas.datacontract.org/2004/07/DianResponse}DianResponse', 
   'ErrorMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}ErrorMessage', 
   'string': '{http://schemas.microsoft.com/2003/10/Serialization/Arrays}string', 
   'IsValid': '{http://schemas.datacontract.org/2004/07/DianResponse}IsValid', 
   'StatusCode': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusCode', 
   'StatusDescription': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusDescription', 
   'StatusMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusMessage'}
GetStatus = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatus', 
   'body': '\n            <wcf:GetStatus>\n                <!--Optional:-->\n                <wcf:trackId>%(trackId)s</wcf:trackId>\n            </wcf:GetStatus>\n        ', 
   'DianResponse': '{http://schemas.datacontract.org/2004/07/DianResponse}DianResponse', 
   'ErrorMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}ErrorMessage', 
   'string': '{http://schemas.microsoft.com/2003/10/Serialization/Arrays}string', 
   'IsValid': '{http://schemas.datacontract.org/2004/07/DianResponse}IsValid', 
   'StatusCode': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusCode', 
   'StatusDescription': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusDescription', 
   'StatusMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusMessage', 
   'XmlDocumentKey': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlDocumentKey', 
   'XmlBase64Bytes': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlBase64Bytes', 
   'IssueTime': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueTime', 
   'IssueDate': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueDate', 
   'LineResponse': '{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LineResponse'}
GetNumberingRange = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/GetNumberingRange', 
   'body': '\n          <wcf:GetNumberingRange>\n             <!--Optional:-->\n             <wcf:accountCode>%(company_vat)s</wcf:accountCode>\n             <!--Optional:-->\n             <wcf:accountCodeT>%(company_vat)s</wcf:accountCodeT>\n             <!--Optional:-->\n             <wcf:softwareCode>%(SoftwareID)s</wcf:softwareCode>\n          </wcf:GetNumberingRange>\n        ', 
   'OperationCode': '{http://schemas.datacontract.org/2004/07/NumberRangeResponseList}OperationCode', 
   'OperationDescription': '{http://schemas.datacontract.org/2004/07/NumberRangeResponseList}OperationDescription', 
   'ResponseList': '{http://schemas.datacontract.org/2004/07/NumberRangeResponseList}ResponseList'}
GetXmlByDocumentKey = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/GetXmlByDocumentKey', 
   'body': '\n          <wcf:GetXmlByDocumentKey>\n             <!--Optional:-->\n             <wcf:trackId>%(trackId)s</wcf:trackId>\n          </wcf:GetXmlByDocumentKey>\n        ', 
   'Code': '{http://schemas.datacontract.org/2004/07/EventResponse}Code', 
   'Message': '{http://schemas.datacontract.org/2004/07/EventResponse}Message', 
   'XmlBytesBase64': '{http://schemas.datacontract.org/2004/07/EventResponse}XmlBytesBase64'}

SendEventUpdateStatus = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/SendEventUpdateStatus', 
   'body': '\n            <wcf:SendEventUpdateStatus>\n                <!--Optional:-->\n                <wcf:fileName>%(zip_fileName)s</wcf:fileName>\n                <!--Optional:-->\n                <wcf:contentFile>%(zip_data)s</wcf:contentFile>\n            </wcf:SendEventUpdateStatus>\n        ', 
   'DianResponse': '{http://schemas.datacontract.org/2004/07/DianResponse}DianResponse', 
   'ErrorMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}ErrorMessage', 
   'string': '{http://schemas.microsoft.com/2003/10/Serialization/Arrays}string', 
   'IsValid': '{http://schemas.datacontract.org/2004/07/DianResponse}IsValid', 
   'StatusCode': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusCode', 
   'StatusDescription': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusDescription', 
   'StatusMessage': '{http://schemas.datacontract.org/2004/07/DianResponse}StatusMessage', 
   'XmlDocumentKey': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlDocumentKey', 
   'XmlBase64Bytes': '{http://schemas.datacontract.org/2004/07/DianResponse}XmlBase64Bytes', 
   'IssueTime': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueTime', 
   'IssueDate': '{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueDate', 
   'LineResponse': '{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LineResponse'}   

GetStatusEvent = {'action': 'http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusEvent',
   'body': '\n            <wcf:GetStatusEvent>\n                <!--Optional:-->\n                <wcf:trackId>%(trackId)s</wcf:trackId>\n                </wcf:GetStatusEvent>\n        ',
}