{
    "name": "Purchase Request - Portal",
    "version": "18.0.1.0.0",
    "summary": "Allows collaborators to create and manage purchase requests from the portal",
    "category": "Purchases",
    "author": "Logyca",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "portal",
        "website",
        "purchase",
        "hr",
        "account",
        "logyca",
    ],
    "data": [
        "data/system_parameters.xml",
        "data/mail_template_data.xml",
        "security/ir.model.access.csv",
        "security/portal_purchase_request_security.xml",
        "views/portal_purchase_request_menu.xml",
        "views/portal_purchase_request_templates.xml",
        "views/portal_purchase_request_views.xml",
        "views/purchase_order_views.xml",
        "views/portal_templates.xml",
        "wizard/create_purchase_order_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
